theme: jekyll-theme-cayman
markdown: kramdown
title: George Jieh | Data Science & AI Portfolio
description: Software Engineer specializing in AI/ML, Data Science, and Backend Development
url: https://georgejieh.dev
baseurl: ""

# Social links
linkedin: george-jieh
github: georgejieh
email: george.jieh@gmail.com

# Jekyll settings
permalink: pretty
show_downloads: false

# Custom variables
author:
  name: George Jieh

plugins:
  - jekyll-seo-tag

# Build settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
